import { motion } from "framer-motion";
import { Activity, Brain, CalendarClock, GraduationCap, Search, ShieldCheck, Sparkles, Users } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Button } from "../../components/ui/button";
import { Card } from "../../components/ui/card";
const readiness = [{ week: "W1", score: 48 }, { week: "W2", score: 56 }, { week: "W3", score: 63 }, { week: "W4", score: 72 }];
const activity = [{ name: "Academics", value: 78 }, { name: "Coding", value: 64 }, { name: "Career", value: 52 }, { name: "Projects", value: 81 }];
const events = ["Solved 100th LeetCode problem", "Submitted OS assignment", "Pushed React analytics dashboard", "AWS certification added"];
export function Dashboard() {
  return <main className="min-h-screen bg-[#070b12] text-slate-100">
    <aside className="fixed inset-y-0 left-0 hidden w-64 border-r border-white/10 bg-[#0b1019] p-5 lg:block"><div className="flex items-center gap-2 text-lg font-semibold"><Brain className="h-5 w-5 text-cyan-300" />Atlas</div><nav className="mt-8 grid gap-1 text-sm text-slate-300">{["Digital Twin","Timeline","AI Mentor","Weekly Wrapped","Mentor View"].map(item => <a className="rounded-md px-3 py-2 hover:bg-white/10" key={item}>{item}</a>)}</nav></aside>
    <section className="lg:pl-64"><header className="sticky top-0 z-10 flex h-16 items-center justify-between border-b border-white/10 bg-[#070b12]/90 px-5 backdrop-blur"><div className="flex min-w-0 items-center gap-3 rounded-md border border-white/10 bg-white/5 px-3 py-2 text-sm text-slate-400"><Search className="h-4 w-4" />Search students, events, skills</div><Button><Sparkles className="h-4 w-4" />Ask AI Mentor</Button></header>
    <div className="mx-auto grid max-w-7xl gap-5 p-5"><motion.div initial={{opacity:0,y:12}} animate={{opacity:1,y:0}} className="grid gap-5 lg:grid-cols-[1.5fr_.9fr]"><Card className="p-5"><div className="mb-5 flex items-start justify-between"><div><p className="text-sm text-cyan-300">Student Digital Twin</p><h1 className="mt-1 text-3xl font-semibold tracking-normal">Placement readiness is improving</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-400">Atlas converts academic, coding, career, and productivity events into live readiness signals and weekly plans.</p></div><ShieldCheck className="h-8 w-8 text-emerald-300" /></div><div className="h-64"><ResponsiveContainer><AreaChart data={readiness}><CartesianGrid strokeDasharray="3 3" stroke="#1f2937"/><XAxis dataKey="week" stroke="#94a3b8"/><YAxis stroke="#94a3b8"/><Tooltip/><Area type="monotone" dataKey="score" stroke="#67e8f9" fill="#0e7490" fillOpacity={0.35}/></AreaChart></ResponsiveContainer></div></Card><Card><h2 className="text-sm font-medium text-slate-300">Today's Focus</h2><div className="mt-4 grid gap-3">{["Complete OS assignment","Practice dynamic programming","Push latest GitHub project","Revise AWS IAM"].map((x,i)=><div key={x} className="flex items-center justify-between rounded-md bg-white/5 px-3 py-2 text-sm"><span>{x}</span><span className="text-slate-500">P{i+1}</span></div>)}</div></Card></motion.div>
    <div className="grid gap-5 md:grid-cols-2 xl:grid-cols-4">{[["Readiness","72",GraduationCap],["Events","184",Activity],["Students at risk","11",Users],["Weekly reports","38",CalendarClock]].map(([label,value,Icon]: any)=><Card key={label}><Icon className="h-5 w-5 text-cyan-300"/><p className="mt-3 text-sm text-slate-400">{label}</p><p className="mt-1 text-2xl font-semibold">{value}</p></Card>)}</div>
    <div className="grid gap-5 lg:grid-cols-[.9fr_1.1fr]"><Card><h2 className="mb-4 font-medium">Intelligence Mix</h2><div className="h-72"><ResponsiveContainer><BarChart data={activity}><CartesianGrid strokeDasharray="3 3" stroke="#1f2937"/><XAxis dataKey="name" stroke="#94a3b8"/><YAxis stroke="#94a3b8"/><Tooltip/><Bar dataKey="value" fill="#a7f3d0" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div></Card><Card><h2 className="font-medium">Timeline Engine</h2><div className="mt-5 grid gap-4">{events.map(event=><div key={event} className="flex gap-3"><div className="mt-1 h-2.5 w-2.5 rounded-full bg-cyan-300"/><div><p className="text-sm font-medium">{event}</p><p className="text-xs text-slate-500">AI summary queued, twin projection updated</p></div></div>)}</div></Card></div></div></section></main>;
}
