import compression from "compression";
import cookieParser from "cookie-parser";
import cors from "cors";
import express from "express";
import rateLimit from "express-rate-limit";
import helmet from "helmet";
import pinoHttp from "pino-http";
import swaggerUi from "swagger-ui-express";
import { env } from "./config/env.js";
import { openApiSpec } from "./docs/openapi.js";
import { logger } from "./lib/logger.js";
import { errorHandler } from "./middleware/errorHandler.js";
import { requestId } from "./middleware/requestId.js";
import { authRoutes } from "./modules/auth/auth.routes.js";
import { eventRoutes } from "./modules/events/event.routes.js";
import { studentRoutes } from "./modules/students/student.routes.js";
export const app = express();
app.use(requestId);
app.use(pinoHttp({ logger }));
app.use(helmet());
app.use(cors({ origin: env.WEB_URL, credentials: true }));
app.use(rateLimit({ windowMs: 60_000, limit: 120 }));
app.use(compression());
app.use(cookieParser());
app.use(express.json({ limit: "1mb" }));
app.get("/health", (_req, res) => res.json({ status: "ok", uptime: process.uptime() }));
app.get("/metrics", (_req, res) => res.type("text/plain").send("# HELP atlas_up Atlas process health\natlas_up 1\n"));
app.use("/docs", swaggerUi.serve, swaggerUi.setup(openApiSpec));
app.use("/api/auth", authRoutes);
app.use("/api/events", eventRoutes);
app.use("/api/students", studentRoutes);
app.use(errorHandler);
